{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "fff0c598_b4583048",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 11
      },
      "lineNbr": 0,
      "author": {
        "id": 1001422
      },
      "writtenOn": "2024-05-13T14:42:12Z",
      "side": 1,
      "message": "`scripts/validate_configs.py` doesn\u0027t know about the introduced association and complains. Do you want to fix that any time soon?",
      "revId": "b02752f7dee06a22b920eecc26849b5dd6fd1d51",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}