{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "c3b654cd_fd374d5a",
        "filename": "scripts/validate_configs.py",
        "patchSetId": 9
      },
      "lineNbr": 168,
      "author": {
        "id": 1000153
      },
      "writtenOn": "2025-04-16T20:47:55Z",
      "side": 1,
      "message": "Now that this ia method, probably don\u0027t want to immediately exit?  Throw an exception maybe?\n\nNot that important.",
      "range": {
        "startLine": 168,
        "startChar": 0,
        "endLine": 168,
        "endChar": 19
      },
      "revId": "ea7a7bc1c608295bbaa7c99419cbc65577fefc80",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "918eafd2_f6965401",
        "filename": "scripts/validate_configs.py",
        "patchSetId": 9
      },
      "lineNbr": 168,
      "author": {
        "id": 1001712
      },
      "writtenOn": "2025-04-24T13:36:00Z",
      "side": 1,
      "message": "Thanks for looking into my patch!\n\nExceptions can be used if we manage any resources which need to be released or cleaned up, or if we can meaningfully recover form the error.\n\nIs there anything we need to clean up here before exiting?\n\nOtherwise i would like to exit quickly, since i do not see how we can recover from the error of not finding the schema file.",
      "parentUuid": "c3b654cd_fd374d5a",
      "range": {
        "startLine": 168,
        "startChar": 0,
        "endLine": 168,
        "endChar": 19
      },
      "revId": "ea7a7bc1c608295bbaa7c99419cbc65577fefc80",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}